<?php

namespace Database\Seeders;

use App\Models\Sql\Countries;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['Vietnam', 'VN', 1, 'VND', 0, 0, 'Asia/Ho_Chi_Minh'],
            ['Philippines', 'PH', 1, 'PHP', 2, 3600, 'Asia/Manila'],
            ['Malaysia', 'MY', 1, 'MYR', 2, 3600, 'Asia/Kuala_Lumpur'],
            ['Singapore', 'SG', 1, 'SGD', 2, 3600, 'Asia/Singapore'],
            ['Indonesia', 'ID', 1, 'IDR', 0, 0, 'Asia/Jakarta'],
            ['Thailand', 'TH', 1, 'THB', 2, 0, 'Asia/Bangkok'],
            ['Afghanistan', 'AF', 1, 'AFN', null, null, null],
            ['Albania', 'AL', 1, 'ALL', null, null, null],
            ['Algeria', 'DZ', 1, 'DZD', null, null, null],
            ['American Samoa', 'AS', 1, 'EUR', null, null, null],
            ['Andorra', 'AD', 1, 'EUR', null, null, null],
            ['Angola', 'AO', 1, 'AOA', null, null, null],
            ['Anguilla', 'AI', 1, 'XCD', null, null, null],
            ['Antigua and Barbuda', 'AG', 1, 'XCD', null, null, null],
            ['Argentina', 'AR', 1, 'ARS', null, null, null],
            ['Armenia', 'AM', 1, 'AMD', null, null, null],
            ['Aruba', 'AW', 1, 'ANG', null, null, null],
            ['Australia', 'AU', 1, 'AUD', null, null, null],
            ['Austria', 'AT', 1, 'EUR', null, null, null],
            ['Azerbaijan', 'AZ', 1, 'AZN', null, null, null],
            ['Bahamas', 'BS', 1, 'BSD', null, null, null],
            ['Bahrain', 'BH', 1, 'BHD', null, null, null],
            ['Bangladesh', 'BD', 1, 'BDT', null, null, null],
            ['Barbados', 'BB', 1, 'BBD', null, null, null],
            ['Belarus', 'BY', 1, 'BYR', null, null, null],
            ['Belgium', 'BE', 1, 'EUR', null, null, null],
            ['Belize', 'BZ', 1, 'BZD', null, null, null],
            ['Benin', 'BJ', 1, 'XOF', null, null, null],
            ['Bermuda', 'BM', 1, 'BMD', null, null, null],
            ['Bhutan', 'BT', 1, 'INR', null, null, null],
            ['Bolivia', 'BO', 1, 'BOB', null, null, null],
            ['Bosnia and Herzegovina', 'BA', 1, 'BAM', null, null, null],
            ['Botswana', 'BW', 1, 'BWP', null, null, null],
            ['Brazil', 'BR', 1, 'BRL', null, null, null],
            ['British Indian Ocean Territory', 'IO', 1, 'USD', null, null, null],
            ['British Virgin Islands', 'VG', 1, 'USD', null, null, null],
            ['Brunei', 'BN', 1, 'BND', null, null, null],
            ['Bulgaria', 'BG', 1, 'BGN', null, null, null],
            ['Burkina Faso', 'BF', 1, 'XOF', null, null, null],
            ['Burundi', 'BI', 1, 'BIF', null, null, null],
            ['Cambodia', 'KH', 1, 'KHR', null, null, null],
            ['Cameroon', 'CM', 1, 'XAF', null, null, null],
            ['Canada', 'CA', 1, 'CAD', null, null, null],
            ['Cape Verde', 'CV', 1, 'CVE', null, null, null],
            ['Caribbean Netherlands', 'BQ', 1, null, null, null, null],
            ['Cayman Islands', 'KY', 1, 'KYD', null, null, null],
            ['Central African Republic', 'CF', 1, 'XAF', null, null, null],
            ['Chad', 'TD', 1, 'XAF', null, null, null],
            ['Chile', 'CL', 1, 'CLP', null, null, null],
            ['China', 'CN', 1, 'CNY', null, null, null],
            ['Christmas Island', 'CX', 1, 'AUD', null, null, null],
            ['Cocos (Keeling) Islands', 'CC', 1, 'AUD', null, null, null],
            ['Colombia', 'CO', 1, 'COP', null, null, null],
            ['Comoros', 'KM', 1, 'KMF', null, null, null],
            ['Congo (DRC) (Jamhuri ya Kidemokrasia ya Kongo)', 'CD', 1, 'CDF', null, null, null],
            ['Congo (Republic) (Congo-Brazzaville)', 'CG', 1, 'XAF', null, null, null],
            ['Cook Islands', 'CK', 1, 'NZD', null, null, null],
            ['Costa Rica', 'CR', 1, 'CRC', null, null, null],
            ['Côte d’Ivoire', 'CI', 1, 'XOF', null, null, null],
            ['Croatia', 'HR', 1, 'HRK', null, null, null],
            ['Cuba', 'CU', 1, 'CUP', null, null, null],
            ['Curaçao', 'CW', 1, null, null, null, null],
            ['Cyprus', 'CY', 1, 'CYP', null, null, null],
            ['Czech Republic', 'CZ', 1, 'CZK', null, null, null],
            ['Denmark', 'DK', 1, 'DKK', null, null, null],
            ['Djibouti', 'DJ', 1, 'DJF', null, null, null],
            ['Dominica', 'DM', 1, 'XCD', null, null, null],
            ['Dominican Republic', 'DO', 1, 'DOP', null, null, null],
            ['Ecuador', 'EC', 1, 'ECS', null, null, null],
            ['Egypt', 'EG', 1, 'EGP', null, null, null],
            ['El Salvador', 'SV', 1, 'SVC', null, null, null],
            ['Equatorial Guinea', 'GQ', 1, 'XAF', null, null, null],
            ['Eritrea', 'ER', 1, 'ETB', null, null, null],
            ['Estonia', 'EE', 1, 'EEK', null, null, null],
            ['Ethiopia', 'ET', 1, 'ETB', null, null, null],
            ['Falkland Islands (Islas Malvinas)', 'FK', 1, 'FKP', null, null, null],
            ['Faroe Islands', 'FO', 1, 'DKK', null, null, null],
            ['Fiji', 'FJ', 1, 'FJD', null, null, null],
            ['Finland', 'FI', 1, 'EUR', null, null, null],
            ['France', 'FR', 1, 'EUR', null, null, null],
            ['French Guiana', 'GF', 1, 'EUR', null, null, null],
            ['French Polynesia', 'PF', 1, 'XPF', null, null, null],
            ['Gabon', 'GA', 1, 'XAF', null, null, null],
            ['Gambia', 'GM', 1, 'GMD', null, null, null],
            ['Georgia', 'GE', 1, 'GEL', null, null, null],
            ['Germany', 'DE', 1, 'EUR', null, null, null],
            ['Ghana', 'GH', 1, 'GHS', null, null, null],
            ['Gibraltar', 'GI', 1, 'GIP', null, null, null],
            ['Greece', 'GR', 1, 'EUR', null, null, null],
            ['Greenland', 'GL', 1, 'DKK', null, null, null],
            ['Grenada', 'GD', 1, 'XCD', null, null, null],
            ['Guadeloupe', 'GP', 1, 'EUR', null, null, null],
            ['Guam', 'GU', 1, 'USD', null, null, null],
            ['Guatemala', 'GT', 1, 'GTQ', null, null, null],
            ['Guernsey', 'GG', 1, 'GGP', null, null, null],
            ['Guinea', 'GN', 1, 'GNF', null, null, null],
            ['Guinea-Bissau', 'GW', 1, 'XOF', null, null, null],
            ['Guyana', 'GY', 1, 'GYD', null, null, null],
            ['Haiti', 'HT', 1, 'HTG', null, null, null],
            ['Honduras', 'HN', 1, 'HNL', null, null, null],
            ['Hong Kong', 'HK', 1, 'HKD', null, null, null],
            ['Hungary', 'HU', 1, 'HUF', null, null, null],
            ['Iceland', 'IS', 1, 'ISK', null, null, null],
            ['India', 'IN', 1, 'INR', null, null, null],
            ['Iran', 'IR', 1, 'IRR', null, null, null],
            ['Iraq', 'IQ', 1, 'IQD', null, null, null],
            ['Ireland', 'IE', 1, 'EUR', null, null, null],
            ['Isle of Man', 'IM', 1, 'GBP', null, null, null],
            ['Israel', 'IL', 1, 'ILS', null, null, null],
            ['Italy', 'IT', 1, 'EUR', null, null, null],
            ['Jamaica', 'JM', 1, 'JMD', null, null, null],
            ['Japan', 'JP', 1, 'JPY', null, null, null],
            ['Jersey', 'JE', 1, 'GBP', null, null, null],
            ['Jordan', 'JO', 1, 'JOD', null, null, null],
            ['Kazakhstan', 'KZ', 1, 'KZT', null, null, null],
            ['Kenya', 'KE', 1, 'KES', null, null, null],
            ['Kiribati', 'KI', 1, 'AUD', null, null, null],
            ['Kosovo', 'XK', 1, null, null, null, null],
            ['Kuwait', 'KW', 1, 'KWD', null, null, null],
            ['Kyrgyzstan', 'KG', 1, 'KGS', null, null, null],
            ['Laos', 'LA', 1, 'LAK', null, null, null],
            ['Latvia', 'LV', 1, 'LVL', null, null, null],
            ['Lebanon', 'LB', 1, 'LBP', null, null, null],
            ['Lesotho', 'LS', 1, 'LSL', null, null, null],
            ['Liberia', 'LR', 1, 'LRD', null, null, null],
            ['Libya', 'LY', 1, 'LYD', null, null, null],
            ['Liechtenstein', 'LI', 1, 'CHF', null, null, null],
            ['Lithuania', 'LT', 1, 'LTL', null, null, null],
            ['Luxembourg', 'LU', 1, 'EUR', null, null, null],
            ['Macau', 'MO', 1, 'MOP', null, null, null],
            ['Macedonia', 'MK', 1, 'MKD', null, null, null],
            ['Madagascar', 'MG', 1, 'MGA', null, null, null],
            ['Malawi', 'MW', 1, 'MWK', null, null, null],
            ['Maldives', 'MV', 1, 'MVR', null, null, null],
            ['Mali', 'ML', 1, 'XOF', null, null, null],
            ['Malta', 'MT', 1, 'MTL', null, null, null],
            ['Marshall Islands', 'MH', 1, 'USD', null, null, null],
            ['Martinique', 'MQ', 1, 'EUR', null, null, null],
            ['Mauritania', 'MR', 1, 'MRO', null, null, null],
            ['Mauritius', 'MU', 1, 'MUR', null, null, null],
            ['Mayotte', 'YT', 1, 'EUR', null, null, null],
            ['Mexico', 'MX', 1, 'MXN', null, null, null],
            ['Micronesia', 'FM', 1, 'USD', null, null, null],
            ['Moldova', 'MD', 1, 'MDL', null, null, null],
            ['Monaco', 'MC', 1, 'EUR', null, null, null],
            ['Mongolia', 'MN', 1, 'MNT', null, null, null],
            ['Montenegro', 'ME', 1, 'EUR', null, null, null],
            ['Montserrat', 'MS', 1, 'XCD', null, null, null],
            ['Morocco', 'MA', 1, 'MAD', null, null, null],
            ['Mozambique', 'MZ', 1, 'MZN', null, null, null],
            ['Myanmar', 'MM', 1, 'MMK', null, null, null],
            ['Namibia', 'NA', 1, 'NAD', null, null, null],
            ['Nauru', 'NR', 1, 'AUD', null, null, null],
            ['Nepal', 'NP', 1, 'NPR', null, null, null],
            ['Netherlands', 'NL', 1, 'EUR', null, null, null],
            ['New Caledonia', 'NC', 1, 'XPF', null, null, null],
            ['New Zealand', 'NZ', 1, 'NZD', null, null, null],
            ['Nicaragua', 'NI', 1, 'NIO', null, null, null],
            ['Niger', 'NE', 1, 'XOF', null, null, null],
            ['Nigeria', 'NG', 1, 'NGN', null, null, null],
            ['Niue', 'NU', 1, 'NZD', null, null, null],
            ['Norfolk Island', 'NF', 1, 'AUD', null, null, null],
            ['North Korea', 'KP', 1, 'KPW', null, null, null],
            ['Northern Mariana Islands', 'MP', 1, 'USD', null, null, null],
            ['Norway', 'NO', 1, 'NOK', null, null, null],
            ['Oman', 'OM', 1, 'OMR', null, null, null],
            ['Pakistan', 'PK', 1, 'PKR', null, null, null],
            ['Palau', 'PW', 1, 'USD', null, null, null],
            ['Palestine', 'PS', 1, 'JOD', null, null, null],
            ['Panama', 'PA', 1, 'PAB', null, null, null],
            ['Papua New Guinea', 'PG', 1, 'PGK', null, null, null],
            ['Paraguay', 'PY', 1, 'PYG', null, null, null],
            ['Peru', 'PE', 1, 'PEN', null, null, null],
            ['Poland', 'PL', 1, 'PLN', null, null, null],
            ['Portugal', 'PT', 1, 'EUR', null, null, null],
            ['Puerto Rico', 'PR', 1, 'USD', null, null, null],
            ['Qatar', 'QA', 1, 'QAR', null, null, null],
            ['Réunion', 'RE', 1, 'EUR', null, null, null],
            ['Romania', 'RO', 1, 'RON', null, null, null],
            ['Russia', 'RU', 1, 'RUB', null, null, null],
            ['Rwanda', 'RW', 1, 'RWF', null, null, null],
            ['Saint Barthélemy', 'BL', 1, 'EUR', null, null, null],
            ['Saint Helena', 'SH', 1, 'GBP', null, null, null],
            ['Saint Kitts and Nevis', 'KN', 1, 'XCD', null, null, null],
            ['Saint Lucia', 'LC', 1, 'XCD', null, null, null],
            ['Saint Martin', 'MF', 1, 'ANG', null, null, null],
            ['Saint Pierre and Miquelon', 'PM', 1, 'EUR', null, null, null],
            ['Saint Vincent and the Grenadines', 'VC', 1, 'XCD', null, null, null],
            ['Samoa', 'WS', 1, 'EUR', null, null, null],
            ['San Marino', 'SM', 1, 'EUR', null, null, null],
            ['São Tomé and Príncipe', 'ST', 1, 'STD', null, null, null],
            ['Saudi Arabia', 'SA', 1, 'SAR', null, null, null],
            ['Senegal', 'SN', 1, 'XOF', null, null, null],
            ['Serbia', 'RS', 1, 'RSD', null, null, null],
            ['Seychelles', 'SC', 1, 'SCR', null, null, null],
            ['Sierra Leone', 'SL', 1, 'SLL', null, null, null],
            ['Sint Maarten', 'SX', 1, null, null, null, null],
            ['Slovakia', 'SK', 1, 'SKK', null, null, null],
            ['Slovenia', 'SI', 1, 'EUR', null, null, null],
            ['Solomon Islands', 'SB', 1, 'SBD', null, null, null],
            ['Somalia', 'SO', 1, 'SOS', null, null, null],
            ['South Africa', 'ZA', 1, 'ZAR', null, null, null],
            ['South Korea', 'KR', 1, 'KRW', null, null, null],
            ['South Sudan', 'SS', 1, null, null, null, null],
            ['Spain', 'ES', 1, 'EUR', null, null, null],
            ['Sri Lanka', 'LK', 1, 'LKR', null, null, null],
            ['Sudan', 'SD', 1, 'SDG', null, null, null],
            ['Suriname', 'SR', 1, 'SRD', null, null, null],
            ['Svalbard and Jan Mayen', 'SJ', 1, 'NOK', null, null, null],
            ['Swaziland', 'SZ', 1, 'SZL', null, null, null],
            ['Sweden', 'SE', 1, 'SEK', null, null, null],
            ['Switzerland', 'CH', 1, 'CHF', null, null, null],
            ['Syria', 'SY', 1, 'SYP', null, null, null],
            ['Taiwan', 'TW', 1, 'TWD', null, null, null],
            ['Tajikistan', 'TJ', 1, 'TJS', null, null, null],
            ['Tanzania', 'TZ', 1, 'TZS', null, null, null],
            ['Timor-Leste', 'TL', 1, null, null, null, null],
            ['Togo', 'TG', 1, 'XOF', null, null, null],
            ['Tokelau', 'TK', 1, 'NZD', null, null, null],
            ['Tonga', 'TO', 1, 'TOP', null, null, null],
            ['Trinidad and Tobago', 'TT', 1, 'TTD', null, null, null],
            ['Tunisia', 'TN', 1, 'TND', null, null, null],
            ['Turkey', 'TR', 1, 'TRY', null, null, null],
            ['Turkmenistan', 'TM', 1, 'TMT', null, null, null],
            ['Turks and Caicos Islands', 'TC', 1, 'USD', null, null, null],
            ['Tuvalu', 'TV', 1, 'AUD', null, null, null],
            ['U.S. Virgin Islands', 'VI', 1, 'USD', null, null, null],
            ['Uganda', 'UG', 1, 'UGX', null, null, null],
            ['Ukraine', 'UA', 1, 'UAH', null, null, null],
            ['United Arab Emirates', 'AE', 1, 'AED', null, null, null],
            ['United Kingdom', 'GB', 1, 'GBP', null, null, null],
            ['United States', 'US', 1, 'USD', null, null, null],
            ['Uruguay', 'UY', 1, 'UYU', null, null, null],
            ['Uzbekistan', 'UZ', 1, 'UZS', null, null, null],
            ['Vanuatu', 'VU', 1, 'VUV', null, null, null],
            ['Vatican City', 'VA', 1, 'EUR', null, null, null],
            ['Venezuela', 'VE', 1, 'VEF', null, null, null],
            ['Wallis and Futuna', 'WF', 1, 'XPF', null, null, null],
            ['Western Sahara', 'EH', 1, 'MAD', null, null, null],
            ['Yemen', 'YE', 1, 'YER', null, null, null],
            ['Zambia', 'ZM', 1, 'ZMK', null, null, null],
            ['Zimbabwe', 'ZW', 1, 'ZWD', null, null, null],
            ['Åland Islands', 'AX', 1, 'EUR', null, null, null]
        ];
        $arr = DB::table('countries')->pluck(Countries::COL_COUNTRIES_NAME, Countries::COL_COUNTRIES_CODE);
        $temp = [];
        foreach ($data as $item) {
            if (!isset($arr[$item[1]])) {
                $arr = [
                    Countries::COL_COUNTRIES_NAME => $item[0],
                    Countries::COL_COUNTRIES_CODE => $item[1],
                    Countries::COL_COUNTRIES_IS_ACTIVE => $item[2],
                    Countries::COL_COUNTRIES_EXCHANGE => $item[3],
                    Countries::COL_COUNTRIES_FORMAT_RIGHT => $item[4],
                    Countries::COL_COUNTRIES_TIMEZONE_TIME_PADDING => $item[5],
                    Countries::COL_COUNTRIES_TIMEZONE => $item[6],
                    Countries::COL_COUNTRIES_CREATED_AT => time(),
                    Countries::COL_COUNTRIES_UPDATED_AT => time(),
                ];
                array_push($temp, $arr);
            }
        }
        if (!empty($temp)) {
            DB::table('countries')->insert($temp);
        }
    }
}
