---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-onex-passport
  namespace: prod
spec:
  selector:
    matchLabels:
      app: prod-onex-passport
  replicas: 1
  minReadySeconds: 120
  template:
    metadata:
      labels:
        app: prod-onex-passport
    spec:
      containers:
        - name: prod-onex-passport
          image: gcr.io/epsilo-285009/onex-passport:latest
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: prod-onex-passport
              mountPath: /usr/share/nginx/html/.env
              subPath: .env
          readinessProbe:
            httpGet:
              path: /api/health-check
              port: 80
            initialDelaySeconds: 5
            failureThreshold: 60
            periodSeconds: 3
      volumes:
        - name: prod-onex-passport
          configMap:
            name: prod-onex-passport
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: DoesNotExist


---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: prod-onex-passport
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prod-onex-passport
  minReplicas: 5
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 90

---
apiVersion: v1
kind: Service
metadata:
  name: prod-onex-passport
  namespace: prod
spec:
  selector:
    app: prod-onex-passport
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

# Deployment cron
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-onex-passport-cron-legacy
  namespace: prod
spec:
  selector:
    matchLabels:
      app: prod-onex-passport-cron-legacy
  replicas: 1
  template:
    metadata:
      labels:
        app: prod-onex-passport-cron-legacy
    spec:
      containers:
        - name: prod-onex-passport-cron-legacy
          image: gcr.io/epsilo-285009/onex-passport:latest
          command: [ "/bin/sh", "-c", "/usr/local/bin/php /usr/share/nginx/html/artisan schedule:work" ]
          resources:
            requests:
              cpu: 1m
              memory: 16Mi
          volumeMounts:
            - name: prod-onex-passport
              mountPath: /usr/share/nginx/html/.env
              subPath: .env
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: cloud.google.com/gke-preemptible
                    operator: DoesNotExist
      volumes:
        - name: prod-onex-passport
          configMap:
            name: prod-onex-passport

